### ISSUE TITLE
Bad Credentials with Login form from Spring Security

### ISSUE THREAD

**Issue by m-kashani** [bitrecycling/reactive-timesheets#1]
Dear @bitrecycling 

Once I installed `./mvnw clean install spring-boot:run -DskipTests`
and went to the http://hostname:8080

I could not pass the login page as it errors as following:

![image](https://user-images.githubusercontent.com/3967516/100302728-f21ca580-2f68-11eb-8f41-32dabc9c29bd.png)

I thought it could be fixed if I play with the SpringSecurityConf.java, and I tried with the [configureGlobal class](
 https://github.com/bitrecycling/reactive-timesheets/blob/875847f13605f02e96e97fdad676e34619cdda8d/src/main/java/de/bitrecycling/timeshizz/security/config/SpringSecurityConf.java#L30) a little bit, as well as I trying the mentioned default username and password: "timeshizz", "user", "password", etc but unfortunately, I could not pass any further.

I really appreciate any help you can provide running this code.

**Comment by bitrecycling** [comment]
Hi Mahdi Kashani,

you're totally right, there is no initial / default user and I did not include a nice way (yet) to create users. However **it is possible to create a user** by using the CreateUserController with a POST request, either using curl or Postman. Assuming you are running the service under localhost:8080 and the desired username is "timesheetsuser1" and the password shall be "notverysecure!" it goes like this:

`curl -X POST http://localhost:8080/user -d '{"name":"timesheetsuser1","password":"notverysecure!"}' -H "Content-Type: application/json"
`

But behold: this version is not handling multiple users well / at all, I just did not continue after it worked well enough for my scenario which is local deployment, single user, h2 database.

If you are interested though, I can provide more functionality / security / multiuser in the near future. You are the first to open an issue, so you have the privilege to make an impact :)
